MVC/MvcSolar/Models/ConsumoEnergetico.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcSolar.Models
{
    public class ConsumoEnergetico
    {
        // props
        public int ConsumoEnergeticoID { get; set; }
        public double Consumo { get; set; }
        public DateTime Data { get; set; }
        public int HabitacaoID { get; set; }

        // nav props
        public Habitacao Habitacao { get; set; }
    }
}

MVC/MvcSolar/Controllers/ConsumoEnergeticosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcSolar.Data;
using MvcSolar.Models;
using MvcSolar.Services;

namespace MvcSolar.Controllers
{
    public class ConsumoEnergeticosController : Controller
    {
        private readonly MvcSolarContext _context;

        public ConsumoEnergeticosController(MvcSolarContext context)
        {
            _context = context;
        }

        public JsonResult ConsumoEnergeticoGrafico()
        {
            var listaPopulacao = ConsumoEnergeticosService.GetConsumoEnergeticos();
            return Json(listaPopulacao);
        }
        // GET: ConsumoEnergeticos
        public async Task<IActionResult> Index()
        {
            var mvcSolarContext = _context.ConsumosEnergeticos.Include(c => c.Habitacao);
            return View(await mvcSolarContext.ToListAsync());
        }


        // GET: ConsumoEnergeticos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consumoEnergetico = await _context.ConsumosEnergeticos
                .Include(c => c.Habitacao)
                .FirstOrDefaultAsync(m => m.ConsumoEnergeticoID == id);
            if (consumoEnergetico == null)
            {
                return NotFound();
            }

            return View(consumoEnergetico);
        }

        // GET: ConsumoEnergeticos/Create
        public IActionResult Create()
        {
            ViewData["HabitacaoID"] = new SelectList(_context.Habitacoes, "HabitacaoID", "HabitacaoID");
            return View();
        }

        // POST: ConsumoEnergeticos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ConsumoEnergeticoID,Consumo,Data,HabitacaoID")] ConsumoEnergetico consumoEnergetico)
        {
            if (ModelState.IsValid)
            {
                _context.Add(consumoEnergetico);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["HabitacaoID"] = new SelectList(_context.Habitacoes, "HabitacaoID", "HabitacaoID", consumoEnergetico.HabitacaoID);
            return View(consumoEnergetico);
        }

        // GET: ConsumoEnergeticos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consumoEnergetico = await _context.ConsumosEnergeticos.FindAsync(id);
            if (consumoEnergetico == null)
            {
                return NotFound();
            }
            ViewData["HabitacaoID"] = new SelectList(_context.Habitacoes, "HabitacaoID", "HabitacaoID", consumoEnergetico.HabitacaoID);
            return View(consumoEnergetico);
        }

        // POST: ConsumoEnergeticos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ConsumoEnergeticoID,Consumo,Data,HabitacaoID")] ConsumoEnergetico consumoEnergetico)
        {
            if (id != consumoEnergetico.ConsumoEnergeticoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(consumoEnergetico);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConsumoEnergeticoExists(consumoEnergetico.ConsumoEnergeticoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["HabitacaoID"] = new SelectList(_context.Habitacoes, "HabitacaoID", "HabitacaoID", consumoEnergetico.HabitacaoID);
            return View(consumoEnergetico);
        }

        // GET: ConsumoEnergeticos/Delete/5
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError=false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consumoEnergetico = await _context.ConsumosEnergeticos
                .AsNoTracking()
                .Include(c => c.Habitacao)
                .FirstOrDefaultAsync(m => m.ConsumoEnergeticoID == id);
            if (consumoEnergetico == null)
            {
                return NotFound();
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] =
                    "Apagar falhou. Tente outra vez, e se o problema persistir, contacte o administrador.";
            }
            return View(consumoEnergetico);
        }

        // POST: ConsumoEnergeticos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var consumoEnergetico = await _context.ConsumosEnergeticos.FindAsync(id);
            if (consumoEnergetico == null)
            {
                return RedirectToAction(nameof(Index));
            }
            try {
            _context.ConsumosEnergeticos.Remove(consumoEnergetico);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                return RedirectToAction(nameof(Delete), new { id = id, saveChangesError = true });
            }
        }

        private bool ConsumoEnergeticoExists(int id)
        {
            return _context.ConsumosEnergeticos.Any(e => e.ConsumoEnergeticoID == id);
        }
    }
}

MVC/MvcSolar/Views/ConsumoEnergeticos/Create.cshtml
@model MvcSolar.Models.ConsumoEnergetico

@{
    ViewData["Title"] = "Create";
}

<h1>Criar</h1>

<h4>ConsumoEnergetico</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Consumo" class="control-label"></label>
                <input asp-for="Consumo" class="form-control" />
                <span asp-validation-for="Consumo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HabitacaoID" class="control-label"></label>
                <select asp-for="HabitacaoID" class ="form-control" asp-items="ViewBag.HabitacaoID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/MvcSolar/Views/ConsumoEnergeticos/Delete.cshtml
@model MvcSolar.Models.ConsumoEnergetico

@{
    ViewData["Title"] = "Delete";
}

<h1>Apagar</h1>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h3>Tem a certeza que quer apagar?</h3>
<div>
    <h4>ConsumoEnergetico</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Consumo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Consumo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Habitacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Habitacao.HabitacaoID)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ConsumoEnergeticoID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

MVC/MvcSolar/Views/ConsumoEnergeticos/Details.cshtml
@model MvcSolar.Models.ConsumoEnergetico

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>ConsumoEnergetico</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Consumo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Consumo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Habitacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Habitacao.HabitacaoID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ConsumoEnergeticoID">Edit</a> |
    <a asp-action="Index">Voltar</a>
</div>

MVC/MvcSolar/Views/ConsumoEnergeticos/Edit.cshtml
@model MvcSolar.Models.ConsumoEnergetico

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>ConsumoEnergetico</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ConsumoEnergeticoID" />
            <div class="form-group">
                <label asp-for="Consumo" class="control-label"></label>
                <input asp-for="Consumo" class="form-control" />
                <span asp-validation-for="Consumo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HabitacaoID" class="control-label"></label>
                <select asp-for="HabitacaoID" class="form-control" asp-items="ViewBag.HabitacaoID"></select>
                <span asp-validation-for="HabitacaoID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/MvcSolar/Views/ConsumoEnergeticos/Index.cshtml
@model IEnumerable<MvcSolar.Models.ConsumoEnergetico>
<title>
    @ViewData["Title"] - Grafico
</title>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>

<script type="text/javascript">


    google.charts.load('current', {packages: ['corechart', 'bar']});
    google.charts.setOnLoadCallback(CarregaDados);

    function CarregaDados() {
        $.ajax({
            url: '@Url.Action("ConsumoEnergeticoGrafico", "ConsumoEnergeticos")',
            dataType: "json",
            type: "GET",
            error: function(xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function(data) {
                GraficoPopulacional(data);
                return false;
            }
        });
        return false;
    }

    function GraficoPopulacional(data) {
        var dataArray = [
            ['Data', 'Consumo']
        ];
        $.each(data, function(i, item) {
            dataArray.push([item.data, item.consumo]);
        });
        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Consumo Energético',
            chartArea: {
                width: '50%'
            },
            colors: ['#b0120a', '#ffab91'],
            hAxis: {
                title: 'Dia',
                minValue: 0
            },
            vAxis: {
                title: 'Valor em watts'
            }
        };
        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
        chart.draw(data, options);
        return false;
    }
</script> 