MVC/MvcSolar/Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcSolar.Models
{
    public class Funcionario : Utilizador
    {
        public int FuncionarioId { get; set; }


        //nav properties
        public ICollection<Manutencao> Manutencoes { get; set; }

        public Utilizador Utilizador { get; set; }
    }
}

MVC/MvcSolar/Controllers/CalendairController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcSolar.Controllers
{
    public class CalendairController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View("CalendairView");
        }
    }
}

MVC/MvcSolar/Controllers/DashboardPaineisController.cs
using Microsoft.AspNetCore.Mvc;
using MvcSolar.Data;
using MvcSolar.Models;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using System;
using System.Linq;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace MvcMovie.Controllers
{
    public class DashboardPaineisController : Controller
    {
        // 
        // GET: /HelloWorld/

        private readonly MvcSolarContext _context;
        private readonly INotyfService _notyf;


        public DashboardPaineisController(MvcSolarContext context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }


        public async Task<IActionResult> IndexAsync()
        {
            var paineis = from s in _context.Paineis
                select s.Estado;

            var count = 0;

            foreach (Estado m in paineis)
            {
                if (m == Estado.Avariado)
                    count++;
            }

            if (count > 0)
                _notyf.Warning("Aviso:\n Existem " + count + " paineis avariados.");

            var mvcSolarContext = _context.Paineis.Include(p => p.Habitacao);
            var lista = await mvcSolarContext.ToListAsync();

            var mvcSolarContext2 = _context.Habitacoes.Include(h => h.Localidade);
            var casas = (await mvcSolarContext2.ToListAsync());

            var dashboard = new Dashboard(lista, casas[0]);


            ViewBag.dashboard = dashboard;
            return View("DashboardPaineis");
        }

        // 
        // GET: /HelloWorld/Welcome/ 

        public string Welcome()
        {
            return "This is the Welcome action method...";
        }
    }
}

MVC/MvcSolar/Controllers/FuncionarioController.cs
using Microsoft.AspNetCore.Mvc;
using MvcSolar.Data;
using MvcSolar.Models;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Text.Encodings.Web;
using System.Threading.Tasks;


namespace MvcMovie.Controllers
{

    public class FuncionarioController : Controller
    {
        // 
        // GET: /HelloWorld/

        private readonly MvcSolarContext _context;

        public FuncionarioController(MvcSolarContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> IndexAsync()
        {

            var mvcSolarContext = _context.Habitacoes.Include(h => h.Localidade);
            var lista = await mvcSolarContext.ToListAsync();
            var locations = new List<Location>();
            foreach(Habitacao h in lista)
            {
                locations.Add(new Location(h.Latitude, h.Longitude));
            }
            ViewBag.locations = locations;
            return View("FuncionariosView");

        }

        // 
        // GET: /HelloWorld/Welcome/ 

        public string Welcome()
        {
            return "This is the Welcome action method...";
        }
    }
}

MVC/MvcSolar/Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcSolar.Data;
using MvcSolar.Models;

namespace MvcSolar.Controllers
{
    public class FuncionariosController : Controller
    {
        private readonly MvcSolarContext _context;

        public FuncionariosController(MvcSolarContext context)
        {
            _context = context;
        }

        // GET: Funcionarios
        public async Task<IActionResult> Index()
        {
            return View(await _context.Funcionarios.ToListAsync());
        }

        // GET: Funcionarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcionario = await _context.Funcionarios
                .FirstOrDefaultAsync(m => m.UtilizadorId == id);
            if (funcionario == null)
            {
                return NotFound();
            }

            return View(funcionario);
        }

        // GET: Funcionarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Funcionarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FuncionarioId,UtilizadorId,Email,Nome,Password,LastTimeOnline,Username")] Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(funcionario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(funcionario);
        }

        // GET: Funcionarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcionario = await _context.Funcionarios.FindAsync(id);
            if (funcionario == null)
            {
                return NotFound();
            }
            return View(funcionario);
        }

        // POST: Funcionarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FuncionarioId,UtilizadorId,Email,Nome,Password,LastTimeOnline,Username")] Funcionario funcionario)
        {
            if (id != funcionario.UtilizadorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(funcionario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FuncionarioExists(funcionario.UtilizadorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(funcionario);
        }

        // GET: Funcionarios/Delete/5
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError=false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcionario = await _context.Funcionarios
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.UtilizadorId == id);
            if (funcionario == null)
            {
                return NotFound();
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] =
                    "Apagar falhou. Tente outra vez, e se o problema persistir, contacte o administrador.";
            }

            return View(funcionario);
        }

        // POST: Funcionarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var funcionario = await _context.Funcionarios.FindAsync(id);
            if (funcionario == null)
            {
                return RedirectToAction(nameof(Index));
            }
            try {
            _context.Funcionarios.Remove(funcionario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                return RedirectToAction(nameof(Delete), new { id = id, saveChangesError = true });
            }
        }

        private bool FuncionarioExists(int id)
        {
            return _context.Funcionarios.Any(e => e.UtilizadorId == id);
        }
    }
}

MVC/MvcSolar/Views/Shared/CalendairView.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="https://cdn.dhtmlx.com/scheduler/edge/dhtmlxscheduler_material.css"
          rel="stylesheet" type="text/css" />
    <script src="https://cdn.dhtmlx.com/scheduler/edge/dhtmlxscheduler.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function(event) {
            // initializing scheduler
            scheduler.init("scheduler_here", new Date(2021,3,18));

            // initiating data loading
            scheduler.load("api/SchedulerController");
            // initializing dataProcessor
            var dp = new dataProcessor("api/SchedulerController");
            // and attaching it to scheduler
            dp.init(scheduler);
            // setting the REST mode for dataProcessor
            dp.setTransactionMode("REST");
        });
    </script>
</head>
<body>
    <div id="scheduler_here" class="dhx_cal_container" style='width:100%; height:100vh;'>
        <div class="dhx_cal_navline">
            <div class="dhx_cal_prev_button">&nbsp;</div>
            <div class="dhx_cal_next_button">&nbsp;</div>
            <div class="dhx_cal_today_button"></div>
            <div class="dhx_cal_date"></div>
            <div class="dhx_cal_tab" name="day_tab"></div>
            <div class="dhx_cal_tab" name="week_tab"></div>
            <div class="dhx_cal_tab" name="month_tab"></div>
        </div>
        <div class="dhx_cal_header"></div>
        <div class="dhx_cal_data"></div>
    </div>
</body>
</html>

MVC/MvcSolar/Views/Shared/DashboardPaineis.cshtml
<head>
    <meta charset="UTF-8">
    <title>loadmapasyncHTML</title>
    <style type='text/css'>
        body {
            margin: 0;
            padding: 0;
            overflow: hidden;
            font-family: 'Segoe UI', Helvetica, Arial, Sans-Serif
        }
    </style>
</head>
<body scroll="yes" style="overflow: scroll">


<br/>

<div class="row">
    <div class="column">
        <img src="@Url.Content("~/Images/bateria.png")" width="200" height="50"/>
    </div>
    <div class="column" style="margin-left: 30px">
        <h2>Bateria: @ViewBag.dashboard.casa.Bateria Kw</h2>
    </div>
    <div class="column" style="margin-left: 50px">
        <img src="@Url.Content("~/Images/producao.png")" width="50" height="50"/>
    </div>
    <div class="column" style="margin-left: 30px">
        <h2>Producao Atual: @ViewBag.dashboard.prodAtual Kw/h</h2>
    </div>
</div>


<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>

<script type="text/javascript">


    google.charts.load('current', { packages: ['corechart', 'bar'] });
    google.charts.setOnLoadCallback(CarregaDados);

    function CarregaDados() {
        $.ajax({
            url: '@Url.Action("ConsumoEnergeticoGrafico", "ConsumoEnergeticos")',
            dataType: "json",
            type: "GET",
            error: function(xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function(data) {
                GraficoPopulacional(data);
                return false;
            }
        });
        return false;
    }

    function GraficoPopulacional(data) {
        var dataArray = [
            ['Data', 'Consumo']
        ];
        $.each(data,
            function(i, item) {
                dataArray.push([item.data, item.consumo]);
            });
        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Consumo Energetico',
            chartArea: {
                width: '50%'
            },
            colors: ['#b0120a', '#ffab91'],
            hAxis: {
                title: 'Dia',
                minValue: 0
            },
            vAxis: {
                title: 'Valor em watts'
            }
        };
        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
        chart.draw(data, options);
        return false;
    }
</script>


@{
    <br/>

    <br/>
    <br/>
    @foreach (var painel in ViewBag.dashboard.paineis)
    {
        <div class="row">
            <div class="column">
                <img src="~/Images/download.png" width="150" height="150"/>
            </div>


            <div class="column" style="margin-left: 50px">
                <h3>Id: @painel.PainelID</h3>
                <h3>Producao prevista: @painel.ProducaoPrevistaHora Kw/h</h3>
                <h3>Modelo: @painel.Modelo</h3>
                <h3>Estado: @painel.Estado</h3>
            </div>
        </div>

        <br/>
    }
}

<br/>
<br/>
<br/>

</body>

MVC/MvcSolar/Views/Shared/FuncionariosView.cshtml
@using MvcSolar.Models

@{
    ViewBag.Title = "Index";
}



<head>
    <title>loadmapasyncHTML</title>
    <style type='text/css'>
        body {
            margin: 0;
            padding: 0;
            overflow: hidden;
            font-family: 'Segoe UI',Helvetica,Arial,Sans-Serif
        }
    </style>
    <meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
    <script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?key=Ag-xqOL2EnR0ivr5Y1dhiLLZSn11Xr9AsHGPnPBa0eAqHHsFfiq6ye7ZsoAS4yaC'></script>
    <script type='text/javascript'>
        var map;
        function loadMapScenario() {
            map = new Microsoft.Maps.Map(document.getElementById('myMap'), {});
            var location, pin;
            @foreach (var location in ViewBag.locations)
                {
                @:location = new Microsoft.Maps.Location(@location.latitude, @location.longitude);
                @:pin = new Microsoft.Maps.Pushpin(location, { color: 'green' });
                @:map.entities.push(pin);
            }


        }


    </script>
</head>
<body onload='loadMapScenario();'>
    <div id='printoutPanel'></div>

    <div id='myMap' style="position:relative;width:100%;height:700px;"></div>
</body>

MVC/MvcSolar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SOL:AR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="DashboardPaineis" asp-action="Index">Dashboard</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calendair" asp-action="Index">Calendário</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionario" asp-action="Index">Mapa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Avarias" asp-action="Index">Avarias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Eventos" asp-action="Index">Eventos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manutencoes" asp-action="Index">Manutenções</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Meteorologias" asp-action="Index">Meteorologia</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Paineis" asp-action="Index">Painéis</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Utilizadores" asp-action="Index">Utilizadores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lembretes" asp-action="Index">Lembretes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SOL:AR - <a asp-area="" asp-controller="DashboardPaineis" asp-action="Index">Dashboard</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("Notyf")
</body>
</html>